language: python # => 1
    python: # => 2
      - "3.7"
    services: # => 3
      - mysql
    env: # => 4
      -DJANGO=3.0.7 DB=sqlite3
    install: # => 5
      - pip install -r djangovue/requirements.txt